stages:
   - build

python:
    stage: build
    only:
        - next
    image: python
    before_script:
        - gcc --version
        - gcov --version
        - python3 --version
    script:
        - make check GCOV=gcov
        - make check-coverage GCOV=gcov
